"""empty message

Revision ID: aba77835c525
Revises: 
Create Date: 2024-12-16 20:30:04.232759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aba77835c525'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characterclass',
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('LENGTH(name) < 50', name='max_length_name'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('source',
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('LENGTH(name) < 50', name='max_length_name'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spellcomponent',
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('LENGTH(name) < 50', name='max_length_name'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spelllevel',
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('level <= 9', name='max_value_spell_level'),
    sa.CheckConstraint('level >= 0', name='min_value_spell_level'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level')
    )
    op.create_table('spellschool',
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('LENGTH(name) < 50', name='max_length_name'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('typedamage',
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('LENGTH(name) < 50', name='max_length_name'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('unitduration',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('LENGTH(name) < 50', name='max_length_name'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('charactersubclass',
    sa.Column('character_class_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('LENGTH(name) < 50', name='max_length_name'),
    sa.ForeignKeyConstraint(['character_class_id'], ['characterclass.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spell',
    sa.Column('range', sa.Integer(), nullable=False),
    sa.Column('next_level', sa.String(), nullable=True),
    sa.Column('ritual', sa.Boolean(), nullable=False),
    sa.Column('concetration', sa.Boolean(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('type_damage_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('LENGTH(name) < 50', name='max_length_name'),
    sa.CheckConstraint('range >= 0', name='min_value_spell_range'),
    sa.ForeignKeyConstraint(['level_id'], ['spelllevel.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['spellschool.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.ForeignKeyConstraint(['type_damage_id'], ['typedamage.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('refspellcharacterclass',
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.Column('character_class_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_class_id'], ['characterclass.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spell_id', 'character_class_id', name='unique_character_classes_for_spell')
    )
    op.create_table('refspellcharactersubclass',
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.Column('character_subclass_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_subclass_id'], ['charactersubclass.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spell_id', 'character_subclass_id', name='unique_character_subclasses_for_spell')
    )
    op.create_table('refspellcomponent',
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['spellcomponent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spell_id', 'component_id', name='unique_components_for_spell')
    )
    op.create_table('spellcastingtime',
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('unit_duration_id', sa.Integer(), nullable=False),
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('count >= 0', name='min_value_spell_casting_time_count'),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_duration_id'], ['unitduration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_duration_id', 'spell_id', name='unique_casting_time_spell')
    )
    op.create_table('spellduration',
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('unit_duration_id', sa.Integer(), nullable=False),
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('count >= 0', name='min_value_spell_duration_count'),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_duration_id'], ['unitduration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_duration_id', 'spell_id', name='unique_unit_duration_spell')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spellduration')
    op.drop_table('spellcastingtime')
    op.drop_table('refspellcomponent')
    op.drop_table('refspellcharactersubclass')
    op.drop_table('refspellcharacterclass')
    op.drop_table('spell')
    op.drop_table('charactersubclass')
    op.drop_table('unitduration')
    op.drop_table('typedamage')
    op.drop_table('spellschool')
    op.drop_table('spelllevel')
    op.drop_table('spellcomponent')
    op.drop_table('source')
    op.drop_table('characterclass')
    # ### end Alembic commands ###
